global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"

scrape_configs:
  - job_name: "tf-serving"
    scrape_interval: 5s
    metrics_path: /monitoring/prometheus/metrics
    scheme: https  # <--- WAJIB ditambahkan
    static_configs:
      - targets: ['loan-approval-prediction-model-production-9556.up.railway.app'] # Port 443 implisit
    tls_config:
      insecure_skip_verify: true  # Skip SSL verification untuk cert Railway
